services:
  - type: web
    name: airalarmbot
    env: python
    pythonVersion: 3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
