services:
  - type: web
    name: airalarmbot
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11
